# Generated by Django 5.2.4 on 2025-07-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_age_customuser_height_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.FloatField(blank=True, null=True)),
                ('target_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_achieved', models.BooleanField(default=False)),
                ('activity_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
