# Generated by Django 5.2.4 on 2025-07-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='activity_achieved',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_minutes',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='weight_achieved',
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_cycling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_swimming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_cycling_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_running_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_swimming_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
